font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

confirm_os_window_close 0
enable_audio_bell no
hide_window_decorations titlebar-only
cursor_shape beam
cursor_blink_interval 0
scrollback_lines 100000
background_opacity 0.93
watch_config_file yes

map ctrl+f launch --stdin-source=@screen_scrollback --type=overlay kitten search --regex
shell_integration enabled




# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
