set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on
set -g escape-time 10
set -g focus-events on
set -g history-limit 100000
set -g set-clipboard on

unbind C-b
set -g prefix C-s
bind C-s send-prefix

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind q confirm-before -p "kill pane #P? (y/n)" kill-pane

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -n S-Left previous-window
bind -n S-Right next-window
bind -n M-H previous-window
bind -n M-L next-window

set -g status off
set -g pane-border-status top
set -g pane-border-format " #I:#P "
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour250

set-window-option -g mode-keys vi
set -g status-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi H send-keys -X start-of-line
bind-key -T copy-mode-vi L send-keys -X end-of-line

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
